### ISSUE TITLE
In tradeoffs with proposed design can you state more clearly if there is an actual tradeoff?

### ISSUE THREAD

**Issue by BoCupp-Microsoft** [siliu1/TSF1#12]
I don't really see any drawbacks being called out in this section.  If there are none consider retitling to "Considerations for TSFTextStore Reuse" and state something about why (at least in theory) you would expect a 1-to-1 relation between the TSFTextStore and editable elements, but why its OK to reuse instead because of (insert practical reasons).

**Comment by siliu1** [comment]
Thanks. I've rephrased the paragraph and changed the section title.
