### ISSUE TITLE
consider rewording "Now TSFTextStore is successful registered with Windows Input Service and is ready to receive function calls to modify content in edit control. "

### ISSUE THREAD

**Issue by gked** [siliu1/TSF1#5]
Consider rewording "Now TSFTextStore is successful registered with Windows Input Service and is ready to receive function calls to modify content in edit control. " into "Once TSFTextStore is successfully registered with Windows Input Service it is ready to receive function calls to modify content in edit control. "

**Comment by siliu1** [comment]
Thanks, fixed in latest commit.
