### ISSUE TITLE
Could you explain counts of key object types relative to each other?

### ISSUE THREAD

**Issue by BoCupp-Microsoft** [siliu1/TSF1#8]
In the browser process how many thread managers, document managers and edit contexts.  Is it 1->1->8 (an edit context for each input type)?  Does the pattern repeat per HWND or per document with a browsing context or something else?

**Comment by siliu1** [comment]
Thread Manager is unique per HWND and ITfDocumentMgr has a 1-to-1 relationship with TSFTextStore. Each TextInputType has its own TSFTextStore. I'll update the document as well.
